name: parkinson
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nvidia/label/cuda-12.6.3::cuda-toolkit
  - cudnn=9.10.1.4
  - libcufft=11.3.0
  - libcurand=10.3.7
  - nccl=2.26.2
  - triton=3.3.1
  - blas=*=openblas
  - libgfortran-ng
  - fftw
  - openmpi
  - pip
